### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by fucksmile** [luca-medeiros/lang-segment-anything#15]
# pip install -U git+https://github.com/luca-medeiros/lang-segment-anything.git
Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple
Collecting git+https://github.com/luca-medeiros/lang-segment-anything.git
  Cloning https://github.com/luca-medeiros/lang-segment-anything.git to /tmp/pip-req-build-_5vr1f57
ERROR: Exception:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 400, in run
    requirement_set = resolver.resolve(
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 155, in unpack_url
    unpack_vcs_link(link, location, verbosity=verbosity)
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 78, in unpack_vcs_link
    vcs_backend.unpack(location, url=hide_url(link.url), verbosity=verbosity)
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/vcs/versioncontrol.py", line 608, in unpack
    self.obtain(location, url=url, verbosity=verbosity)
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/vcs/versioncontrol.py", line 521, in obtain
    self.fetch_new(dest, url, rev_options, verbosity=verbosity)
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/vcs/git.py", line 272, in fetch_new
    if self.get_git_version() >= (2, 17):
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/vcs/git.py", line 104, in get_git_version
    return tuple(int(c) for c in match.groups())
  File "/root/miniconda3/lib/python3.10/site-packages/pip/_internal/vcs/git.py", line 104, in <genexpr>
    return tuple(int(c) for c in match.groups())
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by luca-medeiros** [comment]
Looks that it's related to your environment.
