### ISSUE TITLE
Error Running Lightning App: PytorchStreamReader failed reading zip archive

### ISSUE THREAD

**Issue by PeggyYuchunWang** [luca-medeiros/lang-segment-anything#7]
## Instructions To Reproduce the 🐛 Bug:

1. Background explanation

Error running lightning app on MacOS 13 on Apple M1 chip

`RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

Full error copied below:

```
(sam) pegasus@peggy-mbp lang-segment-anything % lightning run app app.py
Your Lightning App is starting. This won't take long.
/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/groundingdino/models/GroundingDINO/ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
  warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")
/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/groundingdino/models/GroundingDINO/ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
  warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")
INFO: Your app has started. View it in your browser: http://127.0.0.1:7501/view
/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/groundingdino/models/GroundingDINO/ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
  warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")
final text_encoder_type: bert-base-uncased
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Model loaded from /Users/pegasus/.cache/huggingface/hub/models--ShilongLiu--GroundingDINO/snapshots/a94c9b567a2a374598f05c584e96798a170c56fb/groundingdino_swinb_cogcoor.pth 
 => _IncompatibleKeys(missing_keys=[], unexpected_keys=['label_enc.weight'])
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/lightning/app/utilities/proxies.py", line 437, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/lightning/app/utilities/proxies.py", line 418, in __call__
    self.run_once()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/lightning/app/utilities/proxies.py", line 569, in run_once
    self.work.on_exception(e)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/lightning/app/core/work.py", line 625, in on_exception
    raise exception
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/lightning/app/utilities/proxies.py", line 534, in run_once
    ret = self.run_executor_cls(self.work, work_run, self.delta_queue)(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/lightning/app/utilities/proxies.py", line 367, in __call__
    return self.work_run(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/lightning/app/components/serve/gradio_server.py", line 77, in run
    self._model = self.build_model()
  File "/Users/pegasus/Documents/lang-segment-anything/app.py", line 71, in build_model
    model = LangSAM(sam_type)
  File "/Users/pegasus/Documents/lang-segment-anything/lang_sam/lang_sam.py", line 57, in __init__
    self.build_sam(sam_type)
  File "/Users/pegasus/Documents/lang-segment-anything/lang_sam/lang_sam.py", line 66, in build_sam
    sam = sam_model_registry[sam_type](checkpoint=sam_checkpoint)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/segment_anything/build_sam.py", line 15, in build_sam_vit_h
    return _build_sam(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/segment_anything/build_sam.py", line 105, in _build_sam
    state_dict = torch.load(f)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
INFO: Your Lightning App is being stopped. This won't take long.
INFO: Your Lightning App has been stopped successfully!
```

1. Full runnable code or full changes you made:

```
git clone https://github.com/luca-medeiros/lang-segment-anything && cd lang-segment-anything
pip install torch torchvison
pip install -e .
```

3. What exact command you run: `lightning run app app.py`

1. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "full logs" provided above,
please tell us the expected behavior.

## Environment:

- [x] I'm using the latest version!
- [x] Its not a user-side mistake!

**Comment by PeggyYuchunWang** [comment]
Edit: Same error when running library in Python command line:

```
(sam) pegasus@peggy-mbp lang-segment-anything % python
Python 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:12:31) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> from lang_sam import LangSAM
/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/groundingdino/models/GroundingDINO/ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
  warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")
>>> model = LangSAM()
/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
final text_encoder_type: bert-base-uncased
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Model loaded from /Users/pegasus/.cache/huggingface/hub/models--ShilongLiu--GroundingDINO/snapshots/a94c9b567a2a374598f05c584e96798a170c56fb/groundingdino_swinb_cogcoor.pth 
 => _IncompatibleKeys(missing_keys=[], unexpected_keys=['label_enc.weight'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pegasus/Documents/lang-segment-anything/lang_sam/lang_sam.py", line 57, in __init__
    self.build_sam(sam_type)
  File "/Users/pegasus/Documents/lang-segment-anything/lang_sam/lang_sam.py", line 66, in build_sam
    sam = sam_model_registry[sam_type](checkpoint=sam_checkpoint)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/segment_anything/build_sam.py", line 15, in build_sam_vit_h
    return _build_sam(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/segment_anything/build_sam.py", line 105, in _build_sam
    state_dict = torch.load(f)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by luca-medeiros** [comment]
Hi! Thanks for the bug report.
It seems the checkpoint got corrupted during download and every time you try loading it finds it on the cache and loads the broken checkpoint.

Addressing this issue on https://github.com/luca-medeiros/lang-segment-anything/pull/8

**Comment by JinSeoung-Oh** [comment]
@luca-medeiros Hi, first, I want to say thank for your wonderful work.
Actually, I faced with same problem when I run 

<img width="615" alt="스크린샷 2023-05-15 오전 10 31 50" src="https://github.com/luca-medeiros/lang-segment-anything/assets/78573459/87fb666a-4747-4688-99b4-b5c39915bed0">

This is full error log
I think, it is same issue.
So, plz let me know how I can fix this problem.

Thanks and have a nice day! :)

**Comment by JinSeoung-Oh** [comment]
I solved this problem..
At first, I think the link is not correct or link with corrupt thing.
But It is not. I just change the save path for sam checkpoint and it is work
I'm sorry..
