### ISSUE TITLE
Mask Shape Error after Changing Box Threshold and Text threshold

### ISSUE THREAD

**Issue by PeggyYuchunWang** [luca-medeiros/lang-segment-anything#9]
## Instructions To Reproduce the 🐛 Bug:

1. Background explanation

Mask Shape Error after Changing Box Threshold and Text threshold

```
Running on local URL:  http://127.0.0.1:58312

To create a public link, set `share=True` in `launch()`.
Predicting...  vit_h 0.3 0.25 /private/var/folders/4h/162gwqdn6rz_q7s726gct4_80000gp/T/4111474954c6cdc3c501c06c99fa9648e2ac7618/tmp3c_6dacm.png hair
Predicting...  vit_h 0.3 0.25 /private/var/folders/4h/162gwqdn6rz_q7s726gct4_80000gp/T/4111474954c6cdc3c501c06c99fa9648e2ac7618/tmprfwqx47d.png beard
Predicting...  vit_h 0.3 0.25 /private/var/folders/4h/162gwqdn6rz_q7s726gct4_80000gp/T/32d00a9ce7d67b7364d9b931dd5b4e404af43296/tmp03k8nv96.png beard
Predicting...  vit_h 0.3 0.25 /private/var/folders/4h/162gwqdn6rz_q7s726gct4_80000gp/T/32d00a9ce7d67b7364d9b931dd5b4e404af43296/tmpcpbo9923.png hair
Predicting...  vit_h 0.3 0.25 /private/var/folders/4h/162gwqdn6rz_q7s726gct4_80000gp/T/c2451465d4950e1449122dc8a19dd30d994cf32c/tmped82lrpn.png beard
Predicting...  vit_h 0.3 0.25 /private/var/folders/4h/162gwqdn6rz_q7s726gct4_80000gp/T/e7fa26ab6688ecaebd018157977b3c5a1b8778fa/tmpp2mr3x0q.png beard
Predicting...  vit_h 0.5 0.35 /private/var/folders/4h/162gwqdn6rz_q7s726gct4_80000gp/T/e7fa26ab6688ecaebd018157977b3c5a1b8778fa/tmp3pfcrxgn.png beard
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/gradio/blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/gradio/blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/pegasus/Documents/lang-segment-anything/app.py", line 66, in predict
    image = draw_image(image_array, masks, boxes, labels)
  File "/Users/pegasus/Documents/lang-segment-anything/lang_sam/utils.py", line 18, in draw_image
    image = draw_segmentation_masks(image, masks=masks, colors=['cyan'] * len(boxes), alpha=alpha)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/torchvision/utils.py", line 303, in draw_segmentation_masks
    raise ValueError("masks must be of shape (H, W) or (batch_size, H, W)")
ValueError: masks must be of shape (H, W) or (batch_size, H, W)
Predicting...  vit_h 0.5 0.35 /private/var/folders/4h/162gwqdn6rz_q7s726gct4_80000gp/T/e7fa26ab6688ecaebd018157977b3c5a1b8778fa/tmppp8wv2od.png beard
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/gradio/blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/gradio/blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/pegasus/Documents/lang-segment-anything/app.py", line 66, in predict
    image = draw_image(image_array, masks, boxes, labels)
  File "/Users/pegasus/Documents/lang-segment-anything/lang_sam/utils.py", line 18, in draw_image
    image = draw_segmentation_masks(image, masks=masks, colors=['cyan'] * len(boxes), alpha=alpha)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sam/lib/python3.10/site-packages/torchvision/utils.py", line 303, in draw_segmentation_masks
    raise ValueError("masks must be of shape (H, W) or (batch_size, H, W)")
ValueError: masks must be of shape (H, W) or (batch_size, H, W)
```
<img width="1719" alt="Screenshot 2023-04-24 at 11 09 00 PM" src="https://user-images.githubusercontent.com/9244732/234188940-a3fd727d-0451-414b-9411-d532ab5172f1.png">

1. Full runnable code or full changes you made:

```
lightning run app app.py
```
Changed Box Threshold to 0.5 from default
Changed Text threshold to 0.35 from default

3. What exact command you run: `lightning run app app.py`

1. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "full logs" provided above,
please tell us the expected behavior.

## Environment:

- [x] I'm using the latest version!
- [x] Its not a user-side mistake!

**Comment by luca-medeiros** [comment]
Nice catch!
